"""empty message

Revision ID: 3661d8b753a7
Revises: 4b35bb2ef3b1
Create Date: 2020-01-15 00:06:07.067029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3661d8b753a7'
down_revision = '4b35bb2ef3b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_configuration', 'available_amount')
    op.drop_column('user_configuration', 'main_theme')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_configuration', sa.Column('main_theme', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user_configuration', sa.Column('available_amount', mysql.FLOAT(), nullable=False))
    # ### end Alembic commands ###
