"""empty message

Revision ID: 4b35bb2ef3b1
Revises: 
Create Date: 2020-01-08 22:58:00.024098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b35bb2ef3b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_configuration', 'spend_limit',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('user_configuration', 'warning_percent',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'75'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_configuration', 'warning_percent',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'75'"))
    op.alter_column('user_configuration', 'spend_limit',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
