"""empty message

Revision ID: ec1fecb9da44
Revises: 3bb22d519786
Create Date: 2021-03-05 01:47:19.033923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec1fecb9da44'
down_revision = '3bb22d519786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('from_saving', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'operation', 'operation_type', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operation', type_='foreignkey')
    op.drop_column('operation', 'from_saving')
    # ### end Alembic commands ###