"""empty message

Revision ID: dc252b49ac53
Revises: 
Create Date: 2019-12-16 20:10:58.219815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc252b49ac53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('available_amount', sa.Float(), nullable=False),
    sa.Column('main_theme', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_configuration')
    # ### end Alembic commands ###
