"""Initial migration

Revision ID: 14d490af928c
Revises: 
Create Date: 2021-10-01 16:50:47.500129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d490af928c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('from_saving', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'operation', 'operation_type', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operation', type_='foreignkey')
    op.drop_column('operation', 'from_saving')
    # ### end Alembic commands ###
